--
-- PostgreSQL database dump
--

SET statement_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

--
-- Data for Name: contents; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN2', 'ANN', 'Sample - Announcement 1', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN2" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 1.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154906</created><lastModified>20121010154906</lastModified></content>
', '20121010154906', '20121010154906', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN2" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 1.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154906</created><lastModified>20121010154906</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN3', 'ANN', 'Sample - Announcement 2', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN3" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 2.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154906</created><lastModified>20121010154906</lastModified></content>
', '20121010154906', '20121010154906', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN3" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 2.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154906</created><lastModified>20121010154906</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN4', 'ANN', 'Sample - Announcement 3', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN4" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 3.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154906</created><lastModified>20121010154906</lastModified></content>
', '20121010154906', '20121010154907', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN4" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 3.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154906</created><lastModified>20121010154906</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN5', 'ANN', 'Sample - Announcement 4', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN5" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 4.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154907</created><lastModified>20121010154907</lastModified></content>
', '20121010154907', '20121010154907', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN5" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 4.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154907</created><lastModified>20121010154907</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN6', 'ANN', 'Sample - Announcement 5', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN6" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 5.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154907</created><lastModified>20121010154907</lastModified></content>
', '20121010154907', '20121010154907', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN6" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 5.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154907</created><lastModified>20121010154907</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('ANN7', 'ANN', 'Sample - Announcement 6', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN7" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 6.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154907</created><lastModified>20121010154907</lastModified></content>
', '20121010154907', '20121010154907', '<?xml version="1.0" encoding="UTF-8"?>
<content id="ANN7" typecode="ANN" typedescr="Announcement"><descr>Sample - Announcement 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Longtext"><text lang="en">Lorem ipsum for the management of dolor sit amet - 6.</text></attribute><attribute name="StartDate" attributetype="Date"><date>20120621</date></attribute><attribute name="EndDate" attributetype="Date"><date>20120831</date></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Quinoa cardigan bushwick, non PBR aesthetic aliqua.<br /> Put a bird on it artisan terry richardson in, skateboard delectus food truck irure.</p> <p> Fugiat godard odd future scenester messenger bag ut readymade qui.</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154907</created><lastModified>20121010154907</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG8', 'CNG', 'Sample - Hero Unit', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG8" typecode="CNG" typedescr="Generic Content"><descr>Sample - Hero Unit</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Hello, world!</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Learn more »</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154909</created><lastModified>20121010154909</lastModified></content>
', '20121010154909', '20121010154909', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG8" typecode="CNG" typedescr="Generic Content"><descr>Sample - Hero Unit</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Hello, world!</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.</p>]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Learn more »</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154909</created><lastModified>20121010154909</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG9', 'CNG', 'Sample - Lorem Ipsum', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG9" typecode="CNG" typedescr="Generic Content"><descr>Sample - Lorem Ipsum</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Heading</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.org/</urldest></link><text lang="en">Entando.org</text></attribute><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.github.com/entando/</urldest></link><text lang="en">Entando @GitHub</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154909</created><lastModified>20121010154909</lastModified></content>
', '20121010154909', '20121010154909', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG9" typecode="CNG" typedescr="Generic Content"><descr>Sample - Lorem Ipsum</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Heading</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.org/</urldest></link><text lang="en">Entando.org</text></attribute><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.github.com/entando/</urldest></link><text lang="en">Entando @GitHub</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154909</created><lastModified>20121010154909</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS10', 'NWS', 'Sample - News 1', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS10" typecode="NWS" typedescr="News"><descr>Sample - News 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154910</created><lastModified>20121010154910</lastModified></content>
', '20121010154910', '20121010154910', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS10" typecode="NWS" typedescr="News"><descr>Sample - News 1</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 1</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154910</created><lastModified>20121010154910</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS11', 'NWS', 'Sample - News 2', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS11" typecode="NWS" typedescr="News"><descr>Sample - News 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 2</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', '20121010154911', '20121010154911', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS11" typecode="NWS" typedescr="News"><descr>Sample - News 2</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 2</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS12', 'NWS', 'Sample - News 3', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS12" typecode="NWS" typedescr="News"><descr>Sample - News 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 3</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', '20121010154911', '20121010154911', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS12" typecode="NWS" typedescr="News"><descr>Sample - News 3</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 3</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS13', 'NWS', 'Sample - News 4', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS13" typecode="NWS" typedescr="News"><descr>Sample - News 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', '20121010154911', '20121010154911', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS13" typecode="NWS" typedescr="News"><descr>Sample - News 4</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 4</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS14', 'NWS', 'Sample - News 5', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS14" typecode="NWS" typedescr="News"><descr>Sample - News 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 5</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', '20121010154912', '20121010154912', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS14" typecode="NWS" typedescr="News"><descr>Sample - News 5</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 5</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154911</created><lastModified>20121010154911</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('NWS15', 'NWS', 'Sample - News 6', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS15" typecode="NWS" typedescr="News"><descr>Sample - News 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 6</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154912</created><lastModified>20121010154912</lastModified></content>
', '20121010154912', '20121010154912', '<?xml version="1.0" encoding="UTF-8"?>
<content id="NWS15" typecode="NWS" typedescr="News"><descr>Sample - News 6</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Text"><text lang="en">Here come the news 6</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p>
			
			]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Scenester farm-to-table, ethical pinterest DIY quinoa before they sold out cardigan. Wolf sriracha portland ethical freegan. Fingerstache locavore +1 selvage chambray. Flexitarian umami cray quinoa raw denim whatever. American apparel viral vegan DIY polaroid, cosby sweater etsy williamsburg +1 bicycle rights whatever PBR hoodie photo booth. Master cleanse blog mumblecore vice, pork belly fap leggings cosby sweater. Synth whatever put a bird on it lo-fi, stumptown tumblr typewriter helvetica odd future banksy terry richardson post-ironic selvage.</p> <p> Mustache brunch single-origin coffee, pitchfork hoodie messenger bag freegan fixie fingerstache twee ethical pour-over. Stumptown lomo DIY art party organic next level. Squid cliche gentrify mustache. American apparel chambray leggings PBR pour-over skateboard. Mcsweeney&#39;s next level retro tumblr, ethical fanny pack beard. Put a bird on it mustache art party, biodiesel banh mi artisan direct trade thundercats trust fund wayfarers salvia vice authentic. Lo-fi chillwave small batch, organic pour-over williamsburg VHS narwhal leggings ennui ethnic tofu.</p>
			
			]]></hypertext></attribute><attribute name="Picture" attributetype="Image" /><attribute name="Caption" attributetype="Text" /><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Entando.com</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154912</created><lastModified>20121010154912</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('RSL16', 'RSL', 'Sample - Resolution 20', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="RSL16" typecode="RSL" typedescr="Resolution"><descr>Sample - Resolution 20</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Number" attributetype="Number"><number>20</number></attribute><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Longtext"><text lang="en">Examination and approval of Villamarina Balance Sheet 2013</text></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Examination and approval of Villamarina Balance Sheet 2013</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154913</created><lastModified>20121010154913</lastModified></content>
', '20121010154913', '20121010154913', '<?xml version="1.0" encoding="UTF-8"?>
<content id="RSL16" typecode="RSL" typedescr="Resolution"><descr>Sample - Resolution 20</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Number" attributetype="Number"><number>20</number></attribute><attribute name="Date" attributetype="Date"><date>20120613</date></attribute><attribute name="Title" attributetype="Longtext"><text lang="en">Examination and approval of Villamarina Balance Sheet 2013</text></attribute><attribute name="Summary" attributetype="Hypertext"><hypertext lang="en"><![CDATA[
			
			<p> Examination and approval of Villamarina Balance Sheet 2013</p>
			
			]]></hypertext></attribute><list attributetype="Monolist" name="Documents" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>1.0</version><created>20121010154913</created><lastModified>20121010154913</lastModified></content>
', 'free', '1.0', NULL);
INSERT INTO contents (contentid, contenttype, descr, status, workxml, created, lastmodified, onlinexml, maingroup, currentversion, lasteditor) VALUES ('CNG18', 'CNG', 'Welcome', 'PUBLIC', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG18" typecode="CNG" typedescr="Generic Content"><descr>Welcome</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Welcome!</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	What are you waiting for?<br />
	Try the Administration Area!</p>
<p>
	Find out how many things you can customize, create a new content, a new page or even your own user.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	What are you waiting for?<br />
	Try the Administration Area!</p>
<p>
	Find out how many things you can customize, create a new content, a new page or even your own user.</p>
<p>
	Use the <strong>Sign in</strong> drop-down up there in the top bar with the following account:</p>
<p>
	Username: <strong>admin&nbsp;</strong><br />
	Password: <strong>adminadmin</strong></p>
<p>
	Enjoy Entando!</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="17" lang="en" /><text lang="en">Official plaque</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">Entando Town has a very european look.</text></attribute><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Learn more »</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20121010173248</created><lastModified>20121010173823</lastModified></content>
', '20121010173248', '20121010173824', '<?xml version="1.0" encoding="UTF-8"?>
<content id="CNG18" typecode="CNG" typedescr="Generic Content"><descr>Welcome</descr><groups mainGroup="free" /><categories /><attributes><attribute name="Title" attributetype="Text"><text lang="en">Welcome!</text></attribute><attribute name="Abstract" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	What are you waiting for?<br />
	Try the Administration Area!</p>
<p>
	Find out how many things you can customize, create a new content, a new page or even your own user.</p>
]]></hypertext></attribute><attribute name="MainBody" attributetype="Hypertext"><hypertext lang="en"><![CDATA[<p>
	What are you waiting for?<br />
	Try the Administration Area!</p>
<p>
	Find out how many things you can customize, create a new content, a new page or even your own user.</p>
<p>
	Use the <strong>Sign in</strong> drop-down up there in the top bar with the following account:</p>
<p>
	Username: <strong>admin&nbsp;</strong><br />
	Password: <strong>adminadmin</strong></p>
<p>
	Enjoy Entando!</p>
]]></hypertext></attribute><attribute name="Picture" attributetype="Image"><resource resourcetype="Image" id="17" lang="en" /><text lang="en">Official plaque</text></attribute><attribute name="Caption" attributetype="Text"><text lang="en">Entando Town has a very european look.</text></attribute><list attributetype="Monolist" name="Links" nestedtype="Link"><attribute name="Link" attributetype="Link"><link type="external"><urldest>http://www.entando.com/</urldest></link><text lang="en">Learn more »</text></attribute></list><list attributetype="Monolist" name="Attaches" nestedtype="Attach" /></attributes><status>PUBLIC</status><version>2.0</version><lastEditor>admin</lastEditor><created>20121010173248</created><lastModified>20121010173823</lastModified></content>
', 'free', '2.0', 'admin');


--
-- PostgreSQL database dump complete
--

